vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: down

root: Example System
root.width: 400

f0: Power Management
f0.width: 400
root -> f0
f0_container: "" {
  grid-columns: 1
  grid-rows: 3
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  f1: Generate Power
  f1.width: 400
  f2: Store Power
  f2.width: 400
  f3: Distribute Power
  f3.width: 400
}
f0 -> f0_container

f4: Thermal Management
f4.width: 400
root -> f4
f4_container: "" {
  grid-columns: 1
  grid-rows: 2
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  f5: Detect Temperature
  f5.width: 400
  f6: Cool Components
  f6.width: 400
}
f4 -> f4_container

f7: Data Processing
f7.width: 400
root -> f7
f7_container: "" {
  grid-columns: 1
  grid-rows: 3
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  f8: Collect Data
  f8.width: 400
  f9: Transform Data
  f9.width: 400
  f10: Store Data
  f10.width: 400
}
f7 -> f7_container
