vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: down

root: Example System
root.width: 250

p0: Power Subsystem
p0.width: 250
root -> p0
p0_container: "" {
  grid-columns: 3
  grid-rows: 1
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  p1: Solar\nPanel\nAssembly
  p1.width: 150
  p1.height: 150
  p1.shape: circle
  p2: Battery\nPack
  p2.width: 150
  p2.height: 150
  p2.shape: circle
  p3: Power\nDistribution\nUnit
  p3.width: 150
  p3.height: 150
  p3.shape: circle
}
p0 -> p0_container

p4: Thermal Subsystem
p4.width: 250
root -> p4
p4_container: "" {
  grid-columns: 3
  grid-rows: 1
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  p5: Temperature\nSensor\nArray
  p5.width: 150
  p5.height: 150
  p5.shape: circle
  p6: Cooling\nSystem
  p6.width: 150
  p6.height: 150
  p6.shape: circle
}
p4 -> p4_container

p7: Data Subsystem
p7.width: 250
root -> p7
p7_container: "" {
  grid-columns: 3
  grid-rows: 1
  grid-gap: 5
  style: {
    stroke-width: 0
    fill: transparent
  }
  p8: Data\nAcquisition\nModule
  p8.width: 150
  p8.height: 150
  p8.shape: circle
  p9: Processing\nUnit
  p9.width: 150
  p9.height: 150
  p9.shape: circle
  p10: Storage\nModule
  p10.width: 150
  p10.height: 150
  p10.shape: circle
}
p7 -> p7_container
